all: true
recursive: true
packages:
  meek/internal/port/service:
    config:
      dir: "mock/mockservice"
      pkgname: "mockservice"
      filename: "{{.InterfaceName | lower}}.go"

  meek/internal/port/repository:
    config:
      dir: "mock/mockrepository"
      pkgname: "mockrepository"
      filename: "{{.InterfaceName | lower}}.go"
