filename: "{{.InterfaceName | lower}}.go"
structname: "Mock{{.InterfaceName}}"
packages:
  meek/internal/port/repository:
    config:
      recursive: true
      all: true
      dir: "mock/repository/{{.SrcPackageName}}"
      pkgname: "mock{{.SrcPackageName}}"

  meek/internal/port/service:
    config:
      recursive: true
      all: true
      dir: "mock/service/{{.SrcPackageName}}"
      pkgname: "mock{{.SrcPackageName}}"
